:Author: korneliapapp
:Email: pappkornelia@outlook.com
:Date: 20/03/2019
:Revision: version#4
:License: Public Domain

= Project: lightweightchampions/footPedal_arduino

footPedal_sketch uses an input device (a foot pedal) to trigger changes on the neo pixels (light).
This is a demonstration on how to use an input device to trigger changes on neo pixels.

== Step 1: Installation

1. Download this file
2. Beside "New Sketch", import this file to the Online or Offline Arduino CC editor 

== Step 2: Assemble the circuit

Assemble the circuit following the diagram circuit.jpg attached in the same folder

== Step 3: Load the code

Upload the code contained in this sketch onto your board

=== Folder structure

....
 FootPedalArduino               => Arduino sketch folder
  ├── footPedal_sketch.ino       => main Arduino file
  ├── circuit.jpg      => an image of the layout
  └── ReadMe.adoc         => this file
....

=== Author and credits
Code author: Kornelia Papp
Partial credit to Arduino NeoPixel library by Adafruit: > https://github.com/adafruit/Adafruit_NeoPixel

=== Contributing
To contribute to this project please contact korneliapapp > https://id.arduino.cc/korneliapapp


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.

